name: BatchVine
options:
  bundleIdPrefix: com.shimondeitel.wreathmakinglog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "5"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  BatchVine:
    type: application
    platform: iOS
    sources:
      - path: BatchVine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wreathmakinglog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: BatchVine/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BatchVineTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BatchVineTests
      - path: BatchVine.storekit
    dependencies:
      - target: BatchVine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wreathmakinglog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BatchVineUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BatchVineUITests
    dependencies:
      - target: BatchVine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.wreathmakinglog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  BatchVine:
    build:
      targets:
        BatchVine: all
        BatchVineTests: [test]
        BatchVineUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: BatchVine.storekit
    test:
      config: Debug
      storeKitConfiguration: BatchVine.storekit
      targets:
        - BatchVineTests
        - BatchVineUITests
    archive:
      config: Release
